realsense2_camera:
  ros__parameters:
    depth_module.profile: 424x240x6
    rgb_camera.profile: 320x240x6
    enable_depth: true
    enable_color: true
    enable_gyro: true
    enable_accel: true
    gyro_fps: 200
    accel_fps: 63
    depth_module.emitter_enabled: 0
    depth_module.emitter_on_off: false
    depth_module.emitter_always_on: false
